// File generated by Hologram
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPBqhXQvIJGyp3l5u0ub90dnHw0XCUdqs',
    appId: '1:681057727904:web:7ff28a77ac309a65a060c5',
    messagingSenderId: '681057727904',
    projectId: 'l6bt8leh7e7o8r63ggowklgovscixr',
    authDomain: 'l6bt8leh7e7o8r63ggowklgovscixr.firebaseapp.com',
    storageBucket: 'l6bt8leh7e7o8r63ggowklgovscixr.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQx9DhvdbhRgNYojqK9BpGEx2XlszcQuU',
    appId: '1:681057727904:android:860e04d6c70b0954a060c5',
    messagingSenderId: '681057727904',
    projectId: 'l6bt8leh7e7o8r63ggowklgovscixr',
    storageBucket: 'l6bt8leh7e7o8r63ggowklgovscixr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6vzmGpD3LcyCbEGcq-EK7anh6Je68ddY',
    appId: '1:681057727904:ios:3396f1c648daed1ba060c5',
    messagingSenderId: '681057727904',
    projectId: 'l6bt8leh7e7o8r63ggowklgovscixr',
    storageBucket: 'l6bt8leh7e7o8r63ggowklgovscixr.firebasestorage.app',
    iosClientId: '681057727904-eoj4htrav3116pac9esr2g82ep62kvu0.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.CounterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_API_KEY',
    appId: 'REPLACE_WITH_YOUR_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_MESSAGING_SENDER_ID',
    projectId: 'REPLACE_WITH_YOUR_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_YOUR_STORAGE_BUCKET',
    iosClientId: 'REPLACE_WITH_YOUR_IOS_CLIENT_ID',
    iosBundleId: 'REPLACE_WITH_YOUR_IOS_BUNDLE_ID',
  );
}